package com.example.depressiondetectionstandalone.service

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.provider.Settings
import android.provider.Settings.SettingNotFoundException
import android.util.Log
import com.example.depressiondetectionstandalone.data.AppDatabase
import com.example.depressiondetectionstandalone.data.ScreenEntity
import com.example.depressiondetectionstandalone.util.PidManager
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

class ScreenReceiver : BroadcastReceiver() {

    override fun onReceive(context: Context, intent: Intent) {
        val dao = AppDatabase.getInstance(context.applicationContext).dao()

        val status = when (intent.action) {
            Intent.ACTION_SCREEN_ON    -> "ON"
            Intent.ACTION_SCREEN_OFF   -> "OFF"
            Intent.ACTION_USER_PRESENT -> "UNLOCKED"
            else                       -> "UNKNOWN"
        }

        // stable per-device pid
        val pid = PidManager.getOrCreatePid(context.applicationContext)

        // brightness (0..255); guard against SettingNotFoundException
        val brightness: Int? = try {
            Settings.System.getInt(
                context.contentResolver,
                Settings.System.SCREEN_BRIGHTNESS
            )
        } catch (_: SettingNotFoundException) {
            null
        }

        val entity = ScreenEntity(
            // localId is auto-generated by Room; do not set it here
            pid = pid,
            timestamp = System.currentTimeMillis(),
            screen_status = status,
            brightness = brightness,
            // BroadcastReceiver is invoked for screen on/off/unlock; treat as "interactive" when ON/UNLOCKED
            interactive = status == "ON" || status == "UNLOCKED",
            orientation = context.resources.configuration.orientation
        )

        // write on IO dispatcher; receiver returns immediately
        Log.d("DataCollection", "Screen: $entity")
        CoroutineScope(Dispatchers.IO).launch {
            dao.insertScreen(entity)
        }
    }
}
