package com.example.depressiondetectionstandalone.service

import android.app.Service
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.os.IBinder
import android.util.Log
import com.example.depressiondetectionstandalone.data.AppDatabase
import com.example.depressiondetectionstandalone.data.SleepEntity
import com.example.depressiondetectionstandalone.util.PidManager
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.launch

class SleepService : Service() {

    // store last screen-off timestamp (ms)
    private var lastScreenOff: Long? = null

    // reuse a single scope for DB work during service lifetime
    private val serviceScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    // min duration to consider as a sleep segment (30 minutes)
    private val minSleepMillis = 30L * 60L * 1000L

    private val screenReceiver = object : BroadcastReceiver() {
        override fun onReceive(context: Context?, intent: Intent?) {
            when (intent?.action) {
                Intent.ACTION_SCREEN_OFF -> {
                    lastScreenOff = System.currentTimeMillis()
                }
                Intent.ACTION_SCREEN_ON -> {
                    val end = System.currentTimeMillis()
                    val start = lastScreenOff
                    if (start != null) {
                        val duration = end - start
                        if (duration >= minSleepMillis) {
                            val pid = PidManager.getOrCreatePid(applicationContext)
                            val entity = SleepEntity(
                                // localId auto-generated by Room
                                pid = pid,
                                start_timestamp = start,
                                end_timestamp = end,
                                duration = duration,
                                interruptions = 0,          // you can refine later
                                awake_duration = 0,         // refine if you detect wake periods
                                source = "screen_derived"
                            )
                            Log.d("DataCollection", "Sleep: $entity")
                            serviceScope.launch {
                                AppDatabase.getInstance(applicationContext)
                                    .dao()
                                    .insertSleep(entity)
                            }
                        }
                        // reset for next segment
                        lastScreenOff = null
                    }
                }
            }
        }
    }

    override fun onCreate() {
        super.onCreate()
        val filter = IntentFilter().apply {
            addAction(Intent.ACTION_SCREEN_OFF)
            addAction(Intent.ACTION_SCREEN_ON)
        }
        registerReceiver(screenReceiver, filter)
    }

    override fun onDestroy() {
        super.onDestroy()
        try {
            unregisterReceiver(screenReceiver)
        } catch (_: IllegalArgumentException) {
            // already unregistered — ignore
        }
    }

    override fun onBind(intent: Intent?): IBinder? = null
}
