package com.example.depressiondetectionstandalone.service

import android.app.Service
import android.content.Context
import android.content.Intent
import android.hardware.Sensor
import android.hardware.SensorEvent
import android.hardware.SensorEventListener
import android.hardware.SensorManager
import android.os.IBinder
import android.util.Log
import com.example.depressiondetectionstandalone.util.PidManager
import com.example.depressiondetectionstandalone.data.AppDatabase
import com.example.depressiondetectionstandalone.data.StepsEntity
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.launch

class StepsService : Service(), SensorEventListener {

    private lateinit var sensorManager: SensorManager
    private var stepSensor: Sensor? = null

    // cumulative since boot from TYPE_STEP_COUNTER
    private var baselineSteps: Int? = null
    private var lastTotalSteps: Int? = null

    // app-wide scope for DB writes during service lifetime
    private val serviceScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    // simple prefs to persist baseline across process restarts
    private val prefs by lazy {
        getSharedPreferences("steps_prefs", Context.MODE_PRIVATE)
    }

    private fun loadBaseline(): Int? {
        val v = prefs.getInt("baseline_steps", Int.MIN_VALUE)
        return if (v == Int.MIN_VALUE) null else v
    }

    private fun saveBaseline(v: Int) {
        prefs.edit().putInt("baseline_steps", v).apply()
    }

    override fun onCreate() {
        super.onCreate()
        sensorManager = getSystemService(Context.SENSOR_SERVICE) as SensorManager
        stepSensor = sensorManager.getDefaultSensor(Sensor.TYPE_STEP_COUNTER)

        if (stepSensor == null) {
            // no hardware support; stop service gracefully
            stopSelf()
            return
        }

        // restore baseline if we had one
        baselineSteps = loadBaseline()

        sensorManager.registerListener(
            this,
            stepSensor,
            SensorManager.SENSOR_DELAY_NORMAL
        )
    }

    override fun onSensorChanged(event: SensorEvent) {
        if (event.sensor.type != Sensor.TYPE_STEP_COUNTER) return

        val total = event.values[0].toInt()  // cumulative since boot
        val now = System.currentTimeMillis()

        // initialize baseline the first time we see a reading
        if (baselineSteps == null) {
            baselineSteps = total
            saveBaseline(total)
            lastTotalSteps = total
            return
        }

        // if sensor reset (e.g., reboot), re-baseline
        if (total < (lastTotalSteps ?: total)) {
            baselineSteps = total
            saveBaseline(total)
            lastTotalSteps = total
            return
        }

        val base = baselineSteps ?: total
        val sinceBaseline = total - base

        // compute delta since last sample
        val last = lastTotalSteps ?: total
        var diff = total - last
        if (diff < 0) {
            // guard against clock/driver glitches; treat as 0 and re-baseline-ish
            diff = 0
        }

        lastTotalSteps = total

        // if no new steps, skip insert
        if (diff <= 0) return

        val pid = PidManager.getOrCreatePid(applicationContext)
        val dao = AppDatabase.getInstance(applicationContext).dao()

        val entity = StepsEntity(
            // localId auto-generated by Room
            pid = pid,
            timestamp = now,
            steps = diff,
            sensor_accuracy = event.accuracy,
            step_type = "walking"
        )
        Log.d("DataCollection", "Steps: $entity")
        serviceScope.launch {
            dao.insertSteps(entity)
        }
    }

    override fun onAccuracyChanged(sensor: Sensor?, accuracy: Int) {
        // no-op
    }

    override fun onDestroy() {
        super.onDestroy()
        try {
            sensorManager.unregisterListener(this)
        } catch (_: Exception) {
        }
    }

    override fun onBind(intent: Intent?): IBinder? = null
}
